RegisterNetEvent("revivePlayer")
AddEventHandler("revivePlayer", function()
    local playerPed = PlayerPedId()
    SetEntityHealth(playerPed, 200)
    ClearPedBloodDamage(playerPed)
    ResetPedVisibleDamage(playerPed)
    ClearPedLastWeaponDamage(playerPed)
    print("You have been revived!")
end)
